// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsRakMQY8QGWS1F6KaavkbHjbLRys0qDA',
    appId: '1:656462836166:web:b68e7c0f495932c9d602c7',
    messagingSenderId: '656462836166',
    projectId: 'dashboard-appontmine',
    authDomain: 'dashboard-appontmine.firebaseapp.com',
    storageBucket: 'dashboard-appontmine.appspot.com',
    measurementId: 'G-T2BQE4E01K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmqrGwYYsL0UJiYMj1eJlccErAWhvBsMU',
    appId: '1:656462836166:android:c122b5ce66505b95d602c7',
    messagingSenderId: '656462836166',
    projectId: 'dashboard-appontmine',
    storageBucket: 'dashboard-appontmine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIUEv8MgOQOTG53CFNODRV4kYEos2H000',
    appId: '1:656462836166:ios:447d8156fad255a6d602c7',
    messagingSenderId: '656462836166',
    projectId: 'dashboard-appontmine',
    storageBucket: 'dashboard-appontmine.appspot.com',
    iosClientId: '656462836166-q36nq7sou8ep07juqv0qdh0vgb86pglo.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIUEv8MgOQOTG53CFNODRV4kYEos2H000',
    appId: '1:656462836166:ios:5c9a462063033209d602c7',
    messagingSenderId: '656462836166',
    projectId: 'dashboard-appontmine',
    storageBucket: 'dashboard-appontmine.appspot.com',
    iosClientId: '656462836166-651ql3r8p8mbcfdl3n89hctls9v7d2l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointment.RunnerTests',
  );
}
